# Generated by Django 5.0.12 on 2025-03-09 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('all', 'All'), ('waiting', 'Waiting'), ('ready', 'Ready'), ('paid', 'Paid')], default='waiting', max_length=10, verbose_name='Order_status'),
        ),
    ]
